# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# From Minima-3.0 onwards, site.author is expected to be a mapping of attributes instead
# of a simple scalar value:
#author:
#  name: Dr History X
#  email: "doctor.history.x@gmail.com"
title: Dr History X
email: doctor.history.x@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Every day, several times a day, Learn about a new historical event
  that happened on this exact same date.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://drhistoryx.com" # the base hostname & protocol for your site, e.g. http://example.com

# From Minima-3.0 onwards, the social media data is sourced from config key minima.social_links.
# It is a list of key-value pairs, each entry corresponding to a link rendered in the footer.
# For example, to render links to Jekyll GitHub repository and Twitter account (now X), one should have:
minima:
  social_links:
    # - title: Jekyll repository at GitHub
    #   icon: github
    #   url: "https://github.com/jekyll/jekyll"
    - title: Dr History X at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/DrHistoryX"
twitter_username: DrHistoryX
youtube_username: "@DoctorHistoryX"
# github_username:  jekyll

# Enabling comments (via Disqus)
# Optionally, if you have a Disqus account, you can tell Jekyll to use it to show a comments section below each post.
# ⚠️ url, e.g. https://example.com, must be set in you config file for Disqus to work.
# To enable it, after setting the url field, you also need to add the following lines to your Jekyll site:
disqus:
  shortname: drhistoryx


# Build settings
theme: minima
minima:
  skin: auto
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
